spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentsdb
    username: payments
    password: payments
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.hexapay: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
